name: Pin Request
description: Ask to pin a package to a specific version in order to avoid regressions
body:
  - type: markdown
    attributes:
      value: |
        We can pin packages to older, known working versions when a CentOS Stream update regresses the image.
  - type: textarea
    id: package
    attributes:
      label: Describe the Package
      description: Describe the package you want pinned and why
      placeholder: Pin foobar to version 1.2
      value: "Package foobar version 1.2 blew up, we need to revert to 1.1"
    validations:
      required: true
  - type: textarea
    id: package-source
    attributes:
      label: Package NVR or repository (Optional)
      description: Provide the known-good package NVR and its CentOS Stream or EPEL source
      placeholder: package-1.2.3-4.el10 from centos-stream-baseos
      value: "Pin package-1.2.3-4.el10 from centos-stream-baseos"
    validations:
      required: false
