#!/usr/bin/env python3
"""Generate the repository's root ``.packit.yaml``.

Packit is the factory's spec gate, not its build engine. Its whole value here
is turning a recipe into an SRPM in seconds so a malformed spec fails before a
build root is installed and a compiler runs for ten minutes.

That is a deliberate scope, and it is worth being plain about why it is not
more. Packit-as-a-service builds through Copr, and Copr has no CentOS Stream 10
chroot: EL10 packages are built in ``epel-10-*`` or ``alma-kitten+epel-10-*``,
which is a different ABI target from the ``c10s`` base this image is built on.
Making Copr the binary lane would mean building against a root we do not ship,
which is the one thing this factory exists to avoid. So binaries are built in
our own workflow against the pinned ``c10s`` root, and Packit keeps the job it
is good at.

This file is generated. Edit ``config/upstream-sources.json`` and re-run it
rather than hand-editing, because ``tools/validate.py`` compares the rendered
output against what is committed -- a hand edit that is not re-rendered fails
the gate instead of quietly diverging.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.inventory import factory_root, inventory

HEADER = """# Root-level Packit configuration for the GNOME factory.
#
# Generated by tools/render_packit_config.py -- do not edit by hand.
# Re-run it after adding or removing a recipe; `just factory-check` fails if
# the committed file differs from what the inventory renders.
#
# There is deliberately no `jobs:` section. Packit Service would then build in
# Copr on any pull request, and Copr has no CentOS Stream 10 chroot -- EL10 is
# built in epel-10 or alma-kitten+epel-10, which is not the base this image
# ships on. See docs/architecture.md, "What Packit is for here".
actions:
  create-archive:
    - bash -c 'python3 "$(git rev-parse --show-toplevel)/factory/tools/packit_source0.py"'
packages:
"""

ARCHIVE_ACTION = (
    "factory/tools/packit_source0.py",
)


def render(root: Path) -> str:
    records = inventory(root)
    lines = [HEADER.rstrip("\n")]
    for record in sorted(records, key=lambda item: item.name):
        name = record.upstream_name
        lines.append(f"  {record.name}:")
        lines.append(f"    specfile_path: {record.spec.name}")
        lines.append(f"    upstream_package_name: {name}")
        lines.append(f"    downstream_package_name: {name}")
        lines.append("    paths:")
        lines.append(f"      - factory/packages/{record.name}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--write", action="store_true")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file differs from the rendered one",
    )
    args = parser.parse_args()

    root = factory_root(args.root)
    target = root.parent / ".packit.yaml"
    rendered = render(root)

    if args.write:
        target.write_text(rendered)
        print(f"wrote {target} ({len(inventory(root))} packages)")
        return 0

    if args.check:
        if not target.is_file():
            print(f"{target} is missing; run with --write", file=sys.stderr)
            return 1
        committed = target.read_text()
        if committed != rendered:
            print(
                f"{target} does not match what tools/render_packit_config.py "
                f"produces. Re-run with --write.",
                file=sys.stderr,
            )
            return 1
        print(f"{target} matches the inventory ({len(inventory(root))} packages)")
        return 0

    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())